### PR TITLE
KBR-127: resolve the upstream route from the model the body was built from

### PR DESCRIPTION
**Pull request by shelpuk**
Fixes [KBR-127](https://shelpuk.atlassian.net/browse/KBR-127). Found and deliberately deferred while fixing [KBR-7](https://shelpuk.atlassian.net/browse/KBR-7).

## Context for the Product Owner

Kitty Bridge lets one coding agent talk to any model provider. When you point it at a provider, three things have to agree about **which model this request is for**: the request body, the URL it is posted to, and the authentication header.

**They did not agree.** The body was built from the cleaned-up model name; the URL and the auth header were built from the raw name as written in the profile. Where a provider serves different models on different endpoints, the request went to the wrong address with the wrong credentials.

Two ways a user hits this today:

* **A profile with a prefixed model name.** Writing `model: opencode/minimax-m2.5` — which is how OpenCode Go names its own models — sent a correctly-formed Anthropic request to OpenCode's OpenAI-style endpoint, under the wrong auth scheme. That model simply did not work through kitty. On Azure the same shape produced a deployment URL containing an extra path segment, addressing a deployment that cannot exist.
* **A bridge with no profile model at all.** Every OpenCode Go request took the default endpoint regardless of which model the agent asked for. Ask for `minimax-m2.5` and the body was right and the address was wrong.

The fix makes all three read one value, so they cannot drift apart again. There is no configuration change and no migration: profiles that worked keep working, and profiles that were silently broken start working.

**One behaviour deliberately changes.** An Azure bridge with no profile model used to address a literal placeholder deployment (`/openai/deployments/deployment/…`) that no Azure resource serves — it could never succeed. It now addresses the model the agent asked for, which succeeds whenever the deployment is named after the model. Strictly more configurations work than before; none stop working.

**Two things found while reading, both recorded rather than folded in:**

* `X-Kitty-Model` and the session statistics report the profile's model as written, which can now differ from the name actually sent upstream (`opencode/minimax-m2.5` vs `minimax-m2.5`). An attribution defect in its own right. **Not filed** — worth a ticket if you agree it matters, and I did not want to open one on your tracker uninvited.
* `_upstream_body_for`'s docstring claims every re-serialization goes through it, and fifteen sites bypass it. I checked before concluding: the flag those sites would consult is written in exactly one place, and every site there does go through the helper. Overbroad prose, not a defect — so **no ticket**, and the check is written down so nobody repeats it.

**One process note.** This repository has no `SYSTEM_DESIGN.md` for the bridge module, only the test-suite design. I did not author one for a bug fix — KBR-5, KBR-6 and KBR-7 each shipped without one. The design record that *does* cover this area, `TEST_SUITE.md`'s mutation register and routing oracle, **is** updated here, because this change falsifies three of its rows.

---

## The defect

`BridgeServer` had two sources of truth for one question.

`_normalize_model` writes the answer into `cc_request["model"]` — it overrides the agent's model with the profile model, then runs the result through the adapter's `normalize_model_name`. Every decision about the **body** reads that key: `OpenCodeGoAdapter.translate_to_upstream` does, and since KBR-7 so does the thinking-repair carrier in `_upstream_body_for`.

`_build_upstream_url` and `_build_upstream_headers` read `self._active_model` instead — the profile's model, never normalized. Reproduced against the unfixed revision:

```
profile='opencode/minimax-m2.5'  agent='claude-sonnet-4-5'  ->  cc_request['model']='minimax-m2.5'
   path   = https://opencode.ai/zen/go/v1/chat/completions       <- wrong
   auth   = Bearer                                               <- wrong
   body   = messages                                             <- right

profile=None  agent='minimax-m2.5'  ->  cc_request['model']='minimax-m2.5'
   path   = https://opencode.ai/zen/go/v1/chat/completions       <- wrong
   auth   = Bearer                                               <- wrong
   body   = messages                                             <- right

profile='azure/my-deploy'  agent='gpt-4o'  ->  cc_request['model']='my-deploy'
   path   = .../openai/deployments/azure/my-deploy/chat/completions    <- wrong
```

`ProviderAdapter.get_upstream_path`'s own docstring already named its parameter "the **normalized** model identifier". The contract was stated; the callers violated it.

## The fix

Both helpers take the request and read `cc_request.get("model", "")`, exactly as `_upstream_body_for` already does.

The ticket named a second candidate — normalize `_active_model` once at backend selection. Rejected on evidence, not taste: it repairs the prefixed case and leaves the no-profile-model case broken (`_active_model` is still `None`, so both helpers still resolve from `""`), and it adds a *second* normalized copy of the model rather than removing one. A third option the codebase suggests — publish the normalized model into the `_backend_context` ContextVar — is the same objection with no call-site churn to show for it.

A required parameter also makes "resolve a route without saying which request" unrepresentable. `mypy src/kitty` covers the 46 product call sites; the new L2 guard covers the test tree, which mypy does not read.

## Evidence of red

`TEST_SUITE_IMPLEMENTATION_PLAN.md` §16 requires evidence the regression tests fail on the unfixed revision. These tests cannot run at the base revision *as written* — the fix changes a signature, so at base they fail with `TypeError` for a reason that proves nothing.

So the red is isolated instead: keep the new signatures, revert **only** the two lines of logic to `self._active_model or ""`, and run. Every failure is then attributable to the defect and nothing else.

```
FAILED ...::test_a_prefixed_messages_model_routes_to_messages_on_all_three
FAILED ...::test_a_messages_model_from_the_agent_routes_to_messages
FAILED ...::test_a_prefixed_profile_model_does_not_leak_its_prefix_into_the_path
FAILED ...::test_without_a_profile_model_the_agents_model_names_the_deployment
FAILED ...::test_the_helper_does_not_read_the_profile_model[_build_upstream_url]
FAILED ...::test_the_helper_does_not_read_the_profile_model[_build_upstream_headers]
FAILED ...::test_the_helper_reads_the_request_it_was_given[_build_upstream_url]
FAILED ...::test_the_helper_reads_the_request_it_was_given[_build_upstream_headers]
8 failed, 34 passed
```

34 pass in that state — the non-regression directions (`glm-5` in both configurations, Vertex, and the routing-key survival sweep), which is what localises the defect rather than merely flagging it.

## The tests

**`tests/bridge/test_upstream_route_resolution.py`** (L1, by path default) — behavioural. Each case is a pure function of (adapter, profile model, request model), so it is the lowest layer that can prove the claim (§2.2).

* Path, auth and body asserted **together in one test**, because the defect is a *divergence*: each of the three was individually defensible and only their disagreement was the bug.
* Three cases pass before the fix as well as after — `opencode/glm-5`, bare `glm-5`, and Vertex. They are there because the failure mode of this change is *inverting* the routing, which a suite asserting only the broken direction cannot see.
* The Messages/Chat-Completions classifier is re-derived locally rather than imported from `test_wire_shape_honesty.py`, so a defect in that classifier cannot turn these green.
* One invariant this fix *creates* is pinned across all 23 adapters: fourteen of the twenty-three `_build_upstream_url` sites run **after** `translate_to_upstream` on the same dict, so "the request keeps its `model` key" stopped being an implementation detail. `AzureOpenAIAdapter` removes `model` (register entry P6) and is safe only because it builds a copy.

**`tests/test_upstream_route_source_of_truth.py`** (L2) — structural. KBR-127 was not a wrong rule, it was a *second source* for a rule that already existed, and a second source can be reintroduced by a locally reasonable change.

* Forbids `_active_model`, `_model` **and** `_backends` in either helper body. All three reach the same profile string; forbidding only the one the bug used would leave two open doors.
* Requires a read of `cc_request` — absence alone is satisfied by a helper that reads nothing and returns a hardcoded route.
* Sweeps `src/` and `tests/` for no-argument calls.
* Every check has a positive control; the module docstring records the two shapes the guard **cannot** see (an aliased method, and a monkeypatched stand-in) so a green run is not over-read.

L2 rather than L1 on the repo's own rule: `tests/test_egress_coverage.py` classifies a structural scan of source text as L2 and says why — it keeps such a scan out of the L1 set that mutation testing judges. `tests/test_layer_selection.py` pins the L2 file list in both directions and went red until the new file was registered, which is the check working as designed.

## Also corrected, because this change falsifies them

* `_upstream_body_for`'s docstring still said the URL and header helpers read `_active_model`.
* `ProviderAdapter.upstream_wire_is_messages_api_for_model` described its parameter as unnormalized. Since KBR-7 that string is `cc_request["model"]`, which is normalized — and now the path and header helpers read it too.
* `_MESSAGES_MODELS` gains a stated coupling: it is matched against the **normalized** name, so `OpenCodeGoAdapter.normalize_model_name` must keep the dots. Its base class replaces them with hyphens, and delegating upward would restore KBR-127 invisibly, on every model in that set.
* `TEST_SUITE.md` register rows **M14** and **P20**, and §3.3.5's Azure row and its "derive the routing expectation from the configured profile" rule. All four described the destination as built from the profile's model. §3.2.2 makes the register the specification, so leaving them would hand a wrong derivation rule to whoever implements the §3.3.5 routing oracle.

## Reviewed

Two `system-design-reviewer` passes over the requirements before any code was written. The second caught three real errors in my own spec — including a claim about where normalization happens that I had derived from a *lexical* scan (first `_normalize_model` line precedes first `_build_upstream_url` line) and which is false under control flow: every such call sits inside an `if use_custom_transport:` block. The invariant that actually holds is one level up. That correction is in the requirements and in `_make_upstream_request`'s docstring.

## Review round two

The `code-reviewer` ran the full gate against the first commit — **3514 passed**, plus its own mutation checks, and could not find a call site handed the wrong request. It requested changes on one point, and it was right:

The guard's own docstring claimed that a helper *aliased* to a local name was covered by the test that does it. It was not — `_zero_argument_calls` matched attribute calls only, so `real_headers = server._build_upstream_headers` followed by `real_headers()` was invisible, at the single site in the tree taking that shape. The sweep now resolves local aliases, with a positive control. Two smaller ones fixed in the same pass: the file-count sanity check is now per tree rather than an aggregate `> 100` that `src/` alone will soon satisfy, and the `OpenCodeGoAdapter` override docstring gets the same wording correction the base class already had.

## One defect found, filed, and deliberately not fixed here

Chasing that finding turned up something worse. `TestNothingOnTheWireNamesTheProduct::test_body_and_headers_carry_no_vendor_token` — the guard for **invariant I2, Bridge Indistinguishability**, on the header channel — has never actually run its header half. It captures headers through a stand-in over `_build_upstream_headers`, but the same test monkeypatches `_make_upstream_request`, so nothing downstream executes and the stand-in is never invoked:

```
assert captured_headers, "PROBE: the header stand-in never ran"
E  AssertionError: assert {}
```

`assert "kitty" not in json.dumps(captured_headers…)` has been asserting over `{}`. A guard reading green while proving nothing, on one of the three promises §1 of `TEST_SUITE.md` says the suite exists to keep.

It predates this work — KBR-127 only changed that stand-in's signature — and closing it means restructuring how the test spies, which belongs with the invariant it guards rather than with this one. Filed separately.

## Verification

| Check | Result |
|---|---|
| `ruff check .` | clean |
| `mypy src/kitty` | clean, 87 files |
| `lint-imports` | 3 contracts kept |
| CI fast gate | **3538 passed, 2 skipped** |

One deselection locally: `test_connect_target_table[::ffff:0.0.0.0-127.0.0.1]`, which fails identically on `origin/main` on this host and is green on GitHub CI. Pre-existing, unrelated, and untouched by this branch.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01EGkMbEm3wFByrZqVzXANJQ

[KBR-127]: https://shelpuk.atlassian.net/browse/KBR-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KBR-7]: https://shelpuk.atlassian.net/browse/KBR-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by shelpuk** [comment]
## Failed check: `review` — infrastructure, not this branch

```
"api_error_status": 402,
"result": "API Error: 402 {\"error\":{\"message\":\"Insufficient Balance\", ...}}"
"terminal_reason": "api_error"
```

Zero tokens consumed — the automated reviewer never ran. This is the shared API balance, not anything in the diff, and it is currently failing on every open branch:

```
success  feat/kbr-26-register
failure  feat/kbr-28-connect-proxy-fixture
failure  fix/kbr-128-reviewer-design-docs
failure  fix/kbr-132-openssl-skip
failure  fix/kbr-127-route-from-normalized-model
```

Nothing I can do from the code side; it needs the account topped up, then a re-run. **Every other check passes**, including `test / Python 3.10–3.13` (19 min each) and `ci-required`.

No merge conflicts — `mergeable=MERGEABLE`.

---

## Self-review: two further defects found, both filed, neither fixed here

I went back over the change hunting for what it might have missed. Two findings, both the *same root cause as KBR-127* — a consumer reading the un-normalized profile model — in consumers this ticket does not cover.

### KBR-151 — the compaction budget reads the un-normalized model

`_get_max_context_chars` resolves the model's context window from `self._active_model`, and `get_model_context_tokens` only suffix-matches a *bare* name against a *prefixed* catalog entry, never the reverse. So a prefixed profile misses every lookup and silently takes `DEFAULT_CONTEXT_TOKENS`:

```
DEFAULT_CONTEXT_TOKENS = 200000

opencode_go  minimax-m2.5               ->   204,800
opencode_go  opencode/minimax-m2.5      ->   200,000  <- DEFAULT fallback
azure        gpt-4o                     ->   128,000
azure        azure/gpt-4o               ->   200,000  <- DEFAULT fallback
```

The Azure direction is the harmful one: kitty believes it has 200k of room where the model has 128k, so it **does not compact when it should** and sends an oversized request the provider rejects — on exactly the long conversations compaction exists to rescue. The OpenCode direction is conservative (compacts ~2% early), which is milder but still an unnecessary message-fidelity cost.

**Why not fixed here.** Different consumer, different blast radius (compaction budget, invariant I1 — not endpoint and auth), and it needs its own tests around `_get_max_context_chars` and the compaction trigger, plus a decision on whether to normalize at the call site or inside `get_model_context_tokens` (which would also cover `get_balancing_min_context_tokens`). Folding it in would make this PR two changes wearing one hat — the same reason KBR-7's PR deliberately left KBR-126 and KBR-127 alone, which is how this ticket came to exist.

### KBR-147 — the header half of the vendor-token guard has never run

Already described in the PR body. `test_body_and_headers_carry_no_vendor_token` captures headers through a stand-in over `_build_upstream_headers`, but the same test monkeypatches `_make_upstream_request`, so the stand-in is never invoked and the assertion runs against `{}`. A guard for invariant I2 reading green while proving nothing.

### Still not filed, for the product owner

`X-Kitty-Model` and the session statistics report the un-normalized profile model, which after this change can differ from what actually goes upstream. That is an attribution question rather than a defect with a clear right answer, so I would rather you decide than open a ticket on your behalf.

**Comment by shelpuk** [comment]
## Self-review pass — pushed as `8a6b46c`

Went back over the change hunting for what it got wrong. The behaviour held up; what it lacked was a place to say so once, and it had one bug of its own.

### The residual risk, closed with evidence rather than argument

The structural guard proves a call *names* a request — never that it names the **right** one. `self._build_upstream_url(body)`, or a stale dict, passes both the guard and `mypy`, since both are `dict`. That is the actual risk of a mechanical edit across 46 sites, and no static check covers it.

So I probed it dynamically: a temporary assertion inside `_build_upstream_url` that re-normalizing the request it was handed is a no-op — which fails if the dict was normalized for a *previous* backend, or never normalized at all — run across the bridge suite.

```
1 failed, 1320 passed in 1061.92s
```

The one failure is the known host-local `test_connect_target_table[::ffff:0.0.0.0-127.0.0.1]`. **Zero staleness failures.** No call site the tests reach hands either helper the wrong request.

### `_route_model()` — the rule now has one home

"Which model is this request for?" was answered by the same bare dict lookup written out four times: the upstream path, the auth scheme, and the thinking carrier's dialect at both its proactive and reactive sites. The reasoning sat in prose beside each one.

It is now one function. The adapter's `translate_to_upstream` still reads `cc_request["model"]` directly — `kitty.providers` cannot import from `kitty.bridge` — and *that those two halves must agree on one string* is the invariant this ticket is about. It is now written where a reader will find it.

### The guard got stricter, and I measured the strictness

It asserted the helpers "read `cc_request`" — which `cc_request.get("stream")` would satisfy. It now asserts they **call** `_route_model`.

Falsified rather than assumed: a helper that re-derives the model inline, producing the **byte-identical value**, fails the new check and passed the old one.

```
AssertionError: _build_upstream_url does not call _route_model(). The model every
routing decision reads is defined in exactly one place; a helper that re-derives
it inline is the second source of truth KBR-127 removed.
```

Alias detection also learned the annotated spelling (`real: Callable = obj.helper`), each with its own control.

### `build_upstream_headers_for_model` is concrete now

It was an optional hook the bridge found with `hasattr`. An adapter that routes auth per model and forgot to define it would silently receive the default scheme — the same silent-skip KBR-7 removed for the wire-shape sibling, for the reason recorded there. The default ignores the model and answers as `build_upstream_headers` does, so no adapter overrides anything new, and `_build_upstream_headers` drops a `hasattr`, a `cast` and a `type: ignore` to become one line.

### A bug in my own new code

`_route_model` declared `-> str` and returned `None` for `{"model": null}` — nothing validates that field, so it is reachable.

My first fix raised `TypeError`. That was wrong: it turns a malformed request that previously collected a clean error *from the provider* into a 500 *from the bridge*, for input that was already doomed. It now folds `null` and non-strings to `""`, byte-identical to the `_active_model or ""` it replaced, pinned for all four shapes.

### One more invariant pinned

`normalize_request` runs between `_normalize_model` and the route builders at every one of the 46 sites, so an adapter rewriting `model` there would reopen the divergence by a different door. Now asserted across all 23 adapters, alongside the existing `translate_to_upstream` sweep.

---

### Verification

| Check | Result |
|---|---|
| `ruff check .` | clean |
| `mypy src/kitty` | clean, 87 files |
| `lint-imports` | 3 contracts kept |
| CI fast gate | **3570 passed, 2 skipped** (was 3538 — 32 new tests) |

Same single local deselection as before: `test_connect_target_table[::ffff:0.0.0.0-127.0.0.1]`, which fails identically on `origin/main` on this host and is green on GitHub CI.

### Still outstanding, not mine to fix

The `review` check is still red on **HTTP 402 "Insufficient Balance"** with zero tokens consumed — the shared API account, failing across four branches simultaneously. It needs a top-up and a re-run; nothing in the diff will change it.

File: tests/bridge/test_upstream_route_resolution.py [hunk 1]
```diff
@@ -0,0 +1,373 @@
...
+        """A failover re-reads the route from a request already serialized once.
+
+        Fourteen of the twenty-three ``_build_upstream_url`` call sites run after
+        ``translate_to_upstream`` has been called on the same dict, so KBR-127
+        turned "the request keeps its ``model`` key" from an implementation
+        detail into an invariant.  ``AzureOpenAIAdapter`` is the one adapter
+        that removes ``model`` (register entry P6) and it is safe only because
+        it builds a copy; an adapter that popped the key in place would send the
+        failover attempt to the default route with an empty model — KBR-127(b),
+        reappearing on the one path hardest to reproduce.
```
[the remark this answers is not in the document]
Comment (shelpuk) [reply tests/bridge/test_upstream_route_resolution.py]: Thanks — you found a real error in that docstring, and I've rewritten it. But the replacement you proposed asserts the opposite error, so I've not applied it. Measured rather than traced, because we'd each produced a plausible read of the same code.

**Your trace is right about one attempt, and that is not the case the invariant is about.**

Within a single attempt the URL *is* built before the body, exactly as you say. The exposure is **across** attempts: an attempt fails, and a later failover branch rebuilds the URL from the **same `cc_request` object** — which `translate_to_upstream` has already been handed. In `_stream_messages`, URL at 3458 → body at 3460 → (failure) → URL again at 3515, same dict.

So your suggested line — "Every call site builds the URL and headers from `cc_request` before `translate_to_upstream` runs, so today an adapter that popped the key would not directly mis-route" — would be the more dangerous thing to leave in the file: it tells the next maintainer the invariant is theoretical when it is load-bearing.

**The measurement.** I instrumented `_build_upstream_url` to record, by `id(cc_request)`, whether `translate_to_upstream` had already run on that object, and ran `tests/bridge`:

```
KBR127-TRACE url_total=303 url_after_translate_on_same_dict=57
1 failed, 1290 passed in 1060.17s
```

**57 of 303** URL builds land on an already-translated request. Not zero, and not theoretical. (The one failure is the host-local `test_connect_target_table[::ffff:0.0.0.0-127.0.0.1]`, unrelated.)

**Where my docstring was wrong.** It said "fourteen of the twenty-three call sites". The static count is **fifteen** — sites preceded by a translate on the same dict with no intervening rebuild — and I had carried the fourteen over from an earlier review without re-deriving it, which is exactly the mistake worth flagging. Counting *call sites* was also the wrong frame: what matters is *executions after a failover*, which is why your site-by-site read and my number disagreed while both describing real code.

The docstring now states the single-attempt ordering you observed, the cross-attempt re-entry that makes it matter, the corrected static count, and the runtime measurement.

**Comment by shelpuk** [comment]
## The red `test / Python 3.x` jobs were a **semantic merge conflict**, now resolved

Not a test failure — the **Type check** step. This branch alone type-checks; `pull/55/merge` did not.

While this PR was open, [KBR-134](https://github.com/Shelpuk-AI-Technology-Consulting/kitty-bridge/pull/58) landed on `main`. Its 404 branch reports the URL the bridge asked for, so a user who pasted a full endpoint as their base URL can see the doubled path — and it was written against the **old** two-helper signature. Git merges both sides with no conflict markers; the combined tree does not compile:

```
server.py:6517: error: Missing positional argument "cc_request" in call to
"_build_upstream_url" of "BridgeServer"
```

### The guard in this PR found it before mypy was consulted

```
these call sites resolve a route without naming a request:
  src/kitty/bridge/server.py:6517
```

It was added on the argument that `mypy src/kitty` does not read `tests/`. It turns out to also catch cross-branch drift, which was not the reason for writing it.

### The merged branch also reintroduced KBR-127

More important than the signature. The new code read:

```python
path = provider.get_upstream_path(self._active_model or "")
```

That is the un-normalized profile model — **exactly the defect this PR removes**, landing in the error path on the same day the fix did, at the one moment the user is being told to go and check their endpoint. Naming an endpoint the request never used is worse there than almost anywhere else.

### The fix

`_translate_upstream_error` has no request in scope — it serves twelve call sites, most without one — and threading one through all of them to format an error string would be the wrong trade.

It does not need one. Both adapters that set `requires_custom_url` (`custom_openai`, `custom_anthropic`) inherit `get_upstream_path`, which ignores its argument, so the reported route cannot depend on the model. The branch now says so with an explicitly model-independent request rather than reaching for the profile model.

That soundness is an **assumption about the adapter set**, so it is checked rather than trusted:

* `test_no_custom_url_adapter_routes_on_the_model` fails if an adapter ever both requires a custom URL and routes per model — so that lands as a decision, not a wrong error string;
* a second test pins the subject set to `["custom_anthropic", "custom_openai"]`, so the first cannot pass by finding nothing to look at.

### Verification

The full local gate was killed twice by the OOM reaper — this host runs nine agent sessions and a CI runner against 8 GB — so **CI is the authority for the whole suite on this merge**. Locally, on the merged tree:

| Check | Result |
|---|---|
| `ruff check .` | clean |
| `mypy src/kitty` | clean, 87 files |
| `lint-imports` | 3 contracts kept |
| Changed error path + both custom-URL adapters + the route-resolution pair | **264 passed** |
| Every structural contract guard, including the ones `main` just added | **226 passed** |

Prior to the merge, the full gate was green on this branch twice: **3570 passed, 2 skipped**.


[KBR-134]: https://shelpuk.atlassian.net/browse/KBR-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
